### ISSUE TITLE
CF push failed for .NET Core RC2

### ISSUE THREAD

**Issue by emailtowalter** [SteelToeOSS/Configuration#1]
#Hi ...  I got the Steeltoe dev branch 1.0.0-dev-00022 that supports .NET Core RC2. Worked for the local win7 dev machine.

When I try to push to cloud foundry , I got a error message "unable to resolve 'steeltoe.extensions.cinfiguration.cloudfoundry(>=1.0.0-dev-00022)' for '.NETCoreApp, version=v1.0'"

Any idea?

**Comment by dtillman** [comment]
@emailtowalter Have you taken a look at: https://github.com/SteelToeOSS/Samples/tree/dev/Configuration/src/SimpleCloudFoundry

This is a sample that has been updated to the RC2 bits and works on CloudFoundry with Spring Cloud Services Config Server ... 

Also, if you can point me to your code or project on github I can take a look and see what I can find

**Comment by emailtowalter** [comment]
@dtillman ... it is simple hello world. I use VS2015, .NET RC2, SteelToe dev 00022 version. I tred to push to bluemix publix use 
cf push appname - b https://github.com/cloudfoundry-community/asp.net5-buildpack.git

The source code is here : https://github.com/emailtowalter/webappliation5

The error is
...
       log  : ./project.json
       log  : Restore failed in 11917ms.
       Errors in ./project.json
           Unable to resolve 'SteelToe.Extensions.Configuration.CloudFoundry (>=
 1.0.0-dev-00022)' for '.NETCoreApp,Version=v1.0'.
       FAILED: command failed, exit status 1
       FAILED: Restoring dependencies with Dotnet CLI failed, command failed, ex
it status 1
Staging failed: Buildpack compilation step failed

FAILED
BuildpackCompileFailed
"

**Comment by dtillman** [comment]
@emailtowalter 
I don't see a nuget.config file in the project, so the restore done by the buildpack is not checking the SteelToe Dev feed for the package.

Here is a link to the nugget.config used in one of the samples:  
https://github.com/SteelToeOSS/Samples/blob/dev/Configuration/src/SimpleCloudFoundry/nuget.config

You only need the dev feed, not the master feed to pick up the RC2 bits.

Dave

**Comment by emailtowalter** [comment]
It worked. Tha for point me to the right place. 
Before I close th issue, what is th plan to move to main? .net core will b GA on coming Monday.

**Comment by dtillman** [comment]
@emailtowalter I have merged the RC2 bits into master a few days ago

**Comment by emailtowalter** [comment]
Great!
