### ISSUE TITLE
This Configuration extension can't works well.

### ISSUE THREAD

**Issue by chris-fung** [SteeltoeOSS/Configuration#11]
Hi there, this is my code:

var builder = new ConfigurationBuilder()
                //.SetBasePath(configPath)
                .SetBasePath(env.ContentRootPath)
                //.AddJsonFile("database.json", optional: true, reloadOnChange: true)
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables()
                .AddConfigServer(env);
            Configuration = builder.Build();

I found that sometimes the "Configuration" can retrieve values from git repository as expected, but mostly it can't.  BTW, I can visit the config server url like "http://localhost:8888/env/myapp/default" all the time.

**Comment by dtillman** [comment]
@chris-fung : Can you provide any more details of the failure... stack trace .. log output?

**Comment by dtillman** [comment]
Closing due to lack of further detail
