### ISSUE TITLE
ConfigServer URL is built wrongly when a URL resource path is present

### ISSUE THREAD

**Issue by claudineioj** [SteeltoeOSS/Configuration#12]
Suppose that I have an application named **MyDotNetCoreWebApi** using a ConfigServer hosted on http://myserver.com/applications/config.

My appsettings.json looks like:

```
"spring": {
    "application": {
      "name": "MyDotNetCoreWebApi"
    },
    "cloud": {
      "config": {
        "uri": "http://myserver.com/applications/config"
      }
    }
  }
```
Assuming there is a "dev" profile, I can get the configuration properties by sending a GET request to: http://myserver.com/applications/config/MyDotNetCoreWebApi/dev.

However, on method GetConfigServerUri(), Steeltoe is replacing the resource path "/applications/config" by "MyDotNetCoreWebApi/dev". So the URL becomes: http://myserver.com/MyDotNetCoreWebApi/dev.

I believe the expected behavior should be the concatenation instead of the replacement.

PS: I could do a workaround to fix this:
```
"spring": {
    "application": {
      "name": "MyDotNetCoreWebApi"
    },
    "cloud": {
      "config": {
        "uri": "http://myserver.com",
        "name": "/applications/config/MyDotNetCoreWebApi", // workaround
      }
    }
  }
```

**Comment by dtillman** [comment]
@claudineioj,
Thanks, has already been reported... and is currently fixed in the dev branch and available on the dev feed.

I'll be producing a 1.0.1 release soon... and the fix will be included in it.

Thanks again!
Dave
