### ISSUE TITLE
Use IHostingEnvironment.ApplicationName if spring:application:name setting omitted

### ISSUE THREAD

**Issue by maximpashuk** [SteeltoeOSS/Configuration#13]
Using Steeltoe.Extensions.Configuration.ConfigServer version 1.0.1

If you take a look at [ConfigurationSettingsHelper](https://github.com/SteeltoeOSS/Configuration/blob/master/src/Steeltoe.Extensions.Configuration.ConfigServer/ConfigurationSettingsHelper.cs) class.

[GetEnvironment](https://github.com/SteeltoeOSS/Configuration/blob/master/src/Steeltoe.Extensions.Configuration.ConfigServer/ConfigurationSettingsHelper.cs#L144) method uses **IHostingEnvironment.EnvironmentName** property if ```spring:cloud:config:env``` settings is omitted.

Hovewer, [GetApplicationName](https://github.com/SteeltoeOSS/Configuration/blob/master/src/Steeltoe.Extensions.Configuration.ConfigServer/ConfigurationSettingsHelper.cs#L137) method uses ```spring:cloud:config:name``` setting, then ```spring:application:name``` setting, then returns **null**.

As for me it is obvious that GetApplicationName method should also try **IHostingEnvironment.ApplicationName** property, just like in GetEnvironment method.

Also I can see a TODO in code about sensible default app name.
I think IHostingEnvironment.ApplicationName is good candidate.

**Comment by dtillman** [comment]
Thanks @maximpashuk,
I've added your recommendation... it will be in the 1.1.0-RC3 release shortly and the final 1.1.0
Dave
