### ISSUE TITLE
statuscode returning "not found" in RemoteLoadAsync method of Steeltoe.Extensions.Configuration.ConfigServer. ConfigServerConfigurationProvider

### ISSUE THREAD

**Issue by kpurushottamfromdel** [SteeltoeOSS/Configuration#15]
statuscode returning "not found" in RemoteLoadAsync method of Steeltoe.Extensions.Configuration.ConfigServer. ConfigServerConfigurationProvider. The url of config server service provided is correct, even then this is the result. i set aspnetcore_environemt variable to "DEV". How that matters or what is causing issue here?
![image](https://user-images.githubusercontent.com/29476687/29819884-22309198-8ce0-11e7-98b8-ebe354019678.png)

**Comment by dtillman** [comment]
The aspnetcore_environment setting is used by the Steeltoe client as the {profile} value when making requests of the Config Server.  For a better understanding of the Config server, see this documentation:
http://cloud.spring.io/spring-cloud-static/Dalston.SR4/single/spring-cloud.html#_spring_cloud_config_server

Pay particular attention documentation to FIle Based repositories in the docs if your using git as your backend.
