### ISSUE TITLE
Improve testability by enabling VCAP_SERVICES to come from a specified location

### ISSUE THREAD

**Issue by tillig** [SteeltoeOSS/Configuration#16]
In production, the standard `builder.AddCloudFoundry()` configuration mechanism is perfect, grabbing everything from the environment and building the information required.

However, in testing, like when building systems that need to interact with Cloud Foundry settings, it's really hard to specify different values because you have to _actually set a real environment variable_ to get this to work. It'd be way nicer if you could provide the data somehow, at least in a testing scenario. That'd also help for local development where you're in VS on your local machine and need to test out VCAP stuff. (Working in, say, JSON config is easier than fudging `launchSettings.json` and having to escape quotes and such.)

**Comment by jkonicki** [comment]
This was resolved by #17. Closing.
