### ISSUE TITLE
Support for .NET Core 2.0

### ISSUE THREAD

**Issue by FabianHaasjes** [SteeltoeOSS/Configuration#18]
Hi,

while trying to use the cloud configuration, i got following exception using .NET Core 2.0:

System.MissingMethodException occurred
  HResult=0x80131513
  Message=Method not found: 'System.Collections.Generic.IEnumerable`1<Microsoft.Extensions.Configuration.IConfigurationSource> Microsoft.Extensions.Configuration.IConfigurationBuilder.get_Sources()'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at MyService.Startup..ctor(IHostingEnvironment env)

Are there any plans to support .NET Core 2.0 in the future?

**Comment by dtillman** [comment]
@FabianHaasjes 
The 1.1 Steeltoe bits do not support ASP.NET Core 2.0 yet.  We are working on that.  The 1.1 bits do support ASP.NET Core 1.1 running on .NET Core 2.0 if that is all you need ....

We have created 2.0 dev build packages of Steeltoe that should work with ASP.NET Core 2.0 and you can reference those if you want ... https://myget.org/gallery/steeltoedev ... 

If you run into any problems using the dev bits, please let us know and we will try to fix/help.

Dave
