### ISSUE TITLE
How to get the latest configuration information without restarting the client?

### ISSUE THREAD

**Issue by akaxb** [SteeltoeOSS/Configuration#23]
Hello, when I update the configuration file of the configuration center, I need to restart the client to take effect. Therefore, I want to ask whether this function will be implemented in the future.
thankyou

**Comment by TimHess** [comment]
I believe the link above will help you get what you need, and I don't think there's anything else you need from us for this issue, so I'm going to close it - feel free to reopen if I did not adequately answer your question!

**Comment by JustinPealing** [comment]
Hi, not OP but have the same requirement.

`IOptionsSnapshot` doesn't work as-is - if the configuration provider reloads then it will get any updated values, but the Steeltoe configuration provider isn't reloaded automatically.

It would be good if there was some sort of option to reload configuration automatically, it also looks like Spring Config Server supports some sort of [push notification mechanism](https://cloud.spring.io/spring-cloud-config/multi/multi__push_notifications_and_spring_cloud_bus.html), which would be ideal.

**Comment by TimHess** [comment]
Hi @JustinPealing,

You're right, we don't support Spring Config Server initiated reloads yet, but that is [on our backlog](https://www.pivotaltracker.com/story/show/154450485)

Until then, you have a couple options for reloading config:

- Steeltoe Management 2.1.0 includes an endpoint for [refreshing configuration](https://steeltoe-staging.cfapps.io/docs/steeltoe-management/#1-2-11-refresh) (sorry about link to staging docs, we're in a final editing pass and the updates should get to the production site in the next couple days)
- Directly calling [IConfigurationRoot.Reload](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.iconfigurationroot.reload?view=aspnetcore-2.1#Microsoft_Extensions_Configuration_IConfigurationRoot_Reload)

**Comment by JustinPealing** [comment]
Perfect - Thanks
