### ISSUE TITLE
How do I replace the service URI with the service ID to access the configuration center

### ISSUE THREAD

**Issue by akaxb** [SteeltoeOSS/Configuration#26]
HI：
I registered the configuration center as a service on eureka，
![image](https://user-images.githubusercontent.com/6300834/41693988-a02eb726-753a-11e8-9843-ece2f3d68e4d.png)，I found that the Java client could configure the following information：
![image](https://user-images.githubusercontent.com/6300834/41694034-caa527d8-753a-11e8-958a-d9290b442189.png)，I would also like to replace uri =localhost:8888 with service id =spring-cloud-config-server,hope your help ,thanks

**Comment by TimHess** [comment]
Hello @akaxb,

Steeltoe does not currently support discovery-first bootstrapping (https://github.com/spring-cloud/spring-cloud-config/blob/master/docs/src/main/asciidoc/spring-cloud-config.adoc#discovery-first-bootstrap)

**Comment by akaxb** [comment]
So are there any plans for this in the future，thank you

**Comment by TimHess** [comment]
We have _general_ plans to work on feature parity with the Java clients for both Config Server (https://www.pivotaltracker.com/story/show/157221158) and Eureka (https://www.pivotaltracker.com/story/show/157221134), but timelines and scope haven't been set yet - keeping this issue open (and voting if you wish) does help us to prioritize features that need to be included in those efforts

**Comment by daxnet** [comment]
@TimHess 
Hi, I am also facing the same problem right now, since my ConfigServer is also registered to Eureka. I'd like to have my ASP.NET Core app to build and inject the configuration data from ConfigServer discovered by Eureka, when the app is starting up. I found Spring Cloud does support the discovery-first bootstrapping, however it looks like it is missing from Steeltoe Configuration.

Thanks!

**Comment by dtillman** [comment]
@daxnet @akaxb 

FYI, I have added discovery first config server client features into Steeltoe 2.2.
This feature is currently in the dev feed for Steeltoe.
We hope to release 2.2 by the end of 1st Qtr.

Dave
