### ISSUE TITLE
Unable to install "SteelToe.Extensions.Configuration.ConfigServer" for .NET 1.0 core from https://www.myget.org/F/steeltoemaster/api/v3/index.json

### ISSUE THREAD

**Issue by VenkateshSrini** [SteelToeOSS/Configuration#3]
Hi ,
When I tired to add the following reference to my project.son
**"SteelToe.Extensions.Configuration.ConfigServer": "1.0.0-dev-*"**

I get the following error

****log  : Restoring packages for d:\Venkatesh\ASPNETCore\nonVisualStudio\SampleLinu
pp\project.json...
log  : Installing SteelToe.Extensions.Configuration.ConfigServer 1.0.0-master-00014.
log  : Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegration.Tools' in d:\Venkatesh\ASPNETCore\nonVisualStudio\SampleLinu
pp\project.json...
error: Package SteelToe.Extensions.Configuration.ConfigServer 1.0.0-master-00014 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package SteelToe.Extensions.Configuration.ConfigServer 1.0.0-master-00014 supports:
error:   - dnxcore50 (DNXCore,Version=v5.0)
error:   - net451 (.NETFramework,Version=v4.5.1)
error: One or more packages are incompatible with .NETCoreApp,Version=v1.0.
log  : Writing lock file to disk. Path: d:\Venkatesh\ASPNETCore\nonVisualStudio\SampleLinu
pp\project.lock.json
log  : d:\Venkatesh\ASPNETCore\nonVisualStudio\SampleLinu
pp\project.json
log  : Restore failed in 9368ms.

Errors in d:\Venkatesh\ASPNETCore\nonVisualStudio\SampleLinu
pp\project.json
    Package SteelToe.Extensions.Configuration.ConfigServer 1.0.0-master-00014 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package SteelToe.Extensions.Configuration.ConfigServer 1.0.0-master-00014 supports:
      - dnxcore50 (DNXCore,Version=v5.0)
      - net451 (.NETFramework,Version=v4.5.1)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
ERROR: Error: Command failed: dotnet restore "d:\Venkatesh\ASPNETCore\nonVisualStudio\SampleLinu
pp\project.json"

Errors in d:\Venkatesh\ASPNETCore\nonVisualStudio\SampleLinu
pp\project.json
    Package SteelToe.Extensions.Configuration.ConfigServer 1.0.0-master-00014 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package SteelToe.Extensions.Configuration.ConfigServer 1.0.0-master-00014 supports:
      - dnxcore50 (DNXCore,Version=v5.0)
      - net451 (.NETFramework,Version=v4.5.1)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.****

**Comment by dtillman** [comment]
@VenkateshSrini Can you provide your project.json and the nuget.config file you are using for the dotnet restore please.
Thanks

**Comment by mavenraven** [comment]
Hey @VenkateshSrini I'm going to close this out for now due to inactivity. If you're still having trouble, feel free to open a new issue. Thanks!
