### ISSUE TITLE
Support for Generichost in net core

### ISSUE THREAD

**Issue by patrickqsos** [SteeltoeOSS/Configuration#34]
Hi, the package for net core works fine in a wep app that uses the [Webhost](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-2.1)

What about net core console apps? a console app uses the [Generichost](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.1). I try to use the package but i didn't succeeded.

```
class Program
    {
        static async Task Main(string[] args)
        {
            var host = new HostBuilder()
                .ConfigureHostConfiguration(configHost =>
                {
                    configHost.SetBasePath(Directory.GetCurrentDirectory());
                    configHost.AddJsonFile("appsettings.json", optional: true);
                    configHost.AddCommandLine(args);
                    // This method requires IHostingEnvironment param which is not available in a net core console app
                    configHost.AddConfigServer();
                })
                .ConfigureAppConfiguration((hostContext, configApp) =>
                {
                    configApp.AddJsonFile("appsettings.json", optional: true);
                    configApp.AddJsonFile($"appsettings.{hostContext.HostingEnvironment.EnvironmentName}.json", optional: true);
                    configApp.AddCommandLine(args);
                })
                .ConfigureServices((hostContext, services) =>
                {
                    services.Configure<ConfigServerData>(hostContext.Configuration);
                    services.AddHostedService<AuthJobConsumer>();
                    services.AddSingleton<IAuthResponseProducer, AuthResponseProducer>();
                })
                .ConfigureLogging((hostContext, configLogging) =>
                {
                    configLogging.AddConsoleAdvanced();
                })
                .UseConsoleLifetime()
                .Build();
            await host.RunAsync();
        }
    }
```

Thanks!

**Comment by TimHess** [comment]
Hi @patrickqsos,

Can you elaborate on what didn't work and possibly provide a basic but complete sample app that illustrates the issue, so we can see which libraries and versions you're working with?

Up front, it looks like you're configuring your app configuration twice (under `ConfigureHostConfiguration` and `ConfigureAppConfiguration`) -- you could try the `IConfigurationBuilder.AddConfigServer();` extension, that would go under `.ConfigureAppConfiguration();`

**Comment by patrickqsos** [comment]
Hi @TimHess 

I´ve created an app to reproduce the problem 
https://github.com/patrickqsos/configserverconsole

That app is not meant to be a web app so I´m not using the  **IWebHostBuilder**. Instead I´m using the **IHostBuilder**,  which is useful for hosting apps that don't process HTTP requests.

Thanks!

**Comment by TimHess** [comment]
OK, several things:

1. That project is referencing `Steeltoe.Extensions.Configuration.ConfigServer` version 1.1.1
   1. That should be `Steeltoe.Extensions.Configuration.ConfigServerBase` version 2.1.1
1. I needed to add a reference to `Microsoft.Extensions.Options.ConfigurationExtensions` for `services.Configure<ConfigServerData>(hostContext.Configuration)` to compile
1. Unlikely to be part of your problem, but that appsettings.json wasn't being used as it wasn't getting copied to the output
   1. appsettings.json has a typo (validate_certifates)

After fixing those, I'm able to retrieve config from Spring Cloud Config Server

**Comment by patrickqsos** [comment]
So I was referencing a wrong package. I changed the reference to `Steeltoe.Extensions.Configuration.ConfigServerBase` and it works perfect!

Thank you for your time!.
