### ISSUE TITLE
String concatenation in yml

### ISSUE THREAD

**Issue by Isuama** [SteeltoeOSS/Configuration#35]
Can I perform string concatenation in yml file. 
(https://stackoverflow.com/questions/53184056/string-concatenate-in-yml-file-and-use-with-aspnetcore-2-1)

**Comment by TimHess** [comment]
Steeltoe.Common has several methods for working with Property Placeholders, though one was added in the last several weeks and hasn't made it out to nuget.org yet, and we expect to add another method or two, probably in Steeltoe Configuration, to streamline the overall experience before we release 2.2.

In 2.1 and below, you can already manually resolve placeholders with code like this:
```
string result = PropertyPlaceholderHelper.ResolvePlaceholders("foo=${foo}", someIConfiguration)
```

With the recent addition, you can resolve all placeholders in your `IConfiguration`, though you still have to discretely add the results of placeholder resolution as another config provider, something like 
```
config.AddInMemoryCollection(
               PropertyPlaceholderHelper.GetResolvedConfigurationPlaceholders(config.Build()));
```
Which you can see [demonstrated in the eShopOnContainers Sample](https://github.com/SteeltoeOSS/eShopOnContainers/blob/dev/src/BuildingBlocks/WebHostCustomization/WebHost.Customization/WebHostBuilderExtensions.cs)


[The code is here](https://github.com/SteeltoeOSS/Common/blob/dev/src/Steeltoe.Common/Configuration/PropertyPlaceHolderHelper.cs)

[The tests are here](https://github.com/SteeltoeOSS/Common/blob/dev/test/Steeltoe.Common.Test/Configuration/PropertyPlaceholderHelperTest.cs)

**Comment by TimHess** [comment]
I think the above is a resolution, please re-open if you have further questions
