### ISSUE TITLE
Documentation Appears Incorrect for IOptions<CloudFoundryServicesOptions>

### ISSUE THREAD

**Issue by thnk2wn** [SteeltoeOSS/Configuration#38]
Documentation appears incorrect (maybe from 1.x version) under:
https://steeltoe.io/docs/steeltoe-configuration/#1-2-4-access-configuration-data-as-options

Specifically the example under that heading that follows "The following example controller shows how to do so:"...

The following is no longer valid:
    ServiceOptions.Services[0].Name

This is now a dictionary of type Service not a value of type Service.

Therefore I believe the correct example would be along the lines of:

    ServiceOptions.Services["key"][0]

or 

    ServiceOptions.ServicesList.Single(s => s.Name == "key")

This applies to all of the service related code object use in that sample.

If I'm not missing something I can possibly create a pull request for markdown changes for this later.

**Comment by dtillman** [comment]
Thanks... docs are in process to be updated
