### ISSUE TITLE
Different syntax for accessing credentials in Steeltoe vs. Spring Boot

### ISSUE THREAD

**Issue by skmichaelson** [SteeltoeOSS/Configuration#40]
The syntax for accessing a credential is a bit verbose:

```c sharp
var config = builder.Build();
var name = config["vcap:services:service-name:0:name"]
var uri = config["vcap:services:service-name:0:credentials:uri"]
```

Also, if I have multiple services of the same type, then accessing the 0th element may not be sufficient.

On the other hand, Spring Boot allows users to select services by name:

```java
@Data
@AllArgsConstructor
@Configuration
@ConfigurationProperties("vcap.services.cat_picture_service.credentials")
public class CatPictureServiceProperties {
  private String username;
  private String password;
}
```

Any chance that something similar can be implemented in Steeltoe? Or perhaps the syntax for accessing the config can be updated to match what is used in Spring Boot?

**Comment by TimHess** [comment]
Hi @skmichaelson,

Have you looked at [Connectors](https://github.com/SteeltoeOSS/Connectors)? There's more code for dealing with service bindings in that repository than this one.

@dtillman is currently working on parity between Steeltoe Configuration and Spring Boot, I imagine he'll have some more specific commentary

**Comment by spinfooser** [comment]
I was looking into this a bit more, and found that although a Connector may solve this for postgres or rabbitmq. 

However, there is no connector for using the [CredHub](https://docs.pivotal.io/credhub-service-broker/using.html) service that would be for delivering generic credentials/secrets. 

We have found that a lot of CF users end up needing to connect to external services that aren't provisioned using a tile. So could connectors still be used in this case?

**Comment by TimHess** [comment]
Connectors has a few of the building blocks needed to solve the problem(s) you're facing, but I don't think its quite right at this point for bindings that haven't been pre-defined (such as those you listed). 

@spinfooser, if you could file an issue over in Connectors with any additional information (such as any commonalities in those bindings that aren't currently supported) we could take that idea up over there. 

A CredHub connector shouldn't be _too_ much work, but I don't know yet if that would be a separate feature or not.

**Comment by dtillman** [comment]
@skmichaelson @spinfooser
I added to Steeltoe 2.2 the ability to easily bind Cloud Foundry services to user defined POCO objects. 

The new feature is in the Steeltoe.Extensions.Configuration.CloudFoundry* packages.

I'm hoping this helps with your needs as your should be able to easily define POCO objects that can map to any Cloud Foundry service bindins (e.g. CUPS, CredHub, etc).

We hope to release Steeltoe 2.2 by end of 1st Qtr, but the changes are in the Steeltoe Dev feed now if you'd like to try it out.

To use it:

1. Understand how the [Microsoft Options ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-2.2) framework works.

2. Make sure you have added the CloudFoundry configuration provider to your ConfigurationBuilder.

3. Define a POCO class (e.g. MySqlServiceOptions) which derives from the Steeltoe class [AbstractServiceOptions](https://github.com/SteeltoeOSS/Configuration/blob/dev/src/Steeltoe.Extensions.Configuration.CloudFoundryBase/AbstractServiceOptions.cs).  This class should have properties which map to the VCAP_SERVICES configuration data you want to extract using the normal Microsoft Options framework rules.

4. Use either of the Steeltoe extension methods to add the TOption (e.g. MySqlServiceOptions) to the service  container and also have it configured from the VCAP_SERVICES data.

[ConfigureCloudFoundryService<TOption>(IConfiguration config, string serviceName)](https://github.com/SteeltoeOSS/Configuration/blob/e16edc6b46d03b41124f2ddcdef5d2fbcbdfd7ad/src/Steeltoe.Extensions.Configuration.CloudFoundryCore/CloudFoundryServiceCollectionExtensions.cs#L67)
[ConfigureCloudFoundryServices<TOption>(IConfiguration config, string serviceLabel)](https://github.com/SteeltoeOSS/Configuration/blob/e16edc6b46d03b41124f2ddcdef5d2fbcbdfd7ad/src/Steeltoe.Extensions.Configuration.CloudFoundryCore/CloudFoundryServiceCollectionExtensions.cs#L103)

See the [unit tests](https://github.com/SteeltoeOSS/Configuration/blob/dev/test/Steeltoe.Extensions.Configuration.CloudFoundryCore.Test/CloudFoundryServiceCollectionExtensionsTest.cs) for examples.

Alternatively, if you are not using ASP.NET Core DI, you can also simply new the POCO (e.g. MySqlServiceOptions) and then call the Bind(configuration, serviceName).
