### ISSUE TITLE
Multiple "spring config server" configured in appsettings.json

### ISSUE THREAD

**Issue by jluetolf** [SteeltoeOSS/Configuration#44]
Since there are quite some dependencies on the availability of spring configuration servers,  I'm looking for a way to configure multiple spring configuration servers to provide fallbacks.
In my bootstrap.yml for my spring boot service I configured two configuration servers:

` spring.cloud.config.uri:  http://csvww1160:55003, http://csvww1161:55003`

In case one configuration server is down,  the other one will take over. 
Similar to Java services I'm looking for an option to do this as well for .Net Core 2.1 by configuring following uri in my appsettingsjson:

```
 "spring": {
    "application": {
      "name": "netnumber-orchestration"
    },
    "cloud": {
      "config": {
        "uri": "http://csvww1160:55003,http://csvww1161:55003"
      }
    }
  }
```

This configuration results in a System.UriFormatException: 'Invalid URI: Invalid port specified.' excpetion.
Instead of 
` "uri": "http://csvww1160:55003,http://csvww1161:55003"`
I tried
` "uri": [ "http://csvww1160:55003", "http://csvww1161:55003" ]`
but this is not supported.

Is there a way to configure multiple configuration servers using Steeltoe?

**Comment by TimHess** [comment]
Support for multiple config servers was added in Steeltoe 2.2.0, you can get get the rc2 bits on nuget.org now, a GA release will be out within the next several weeks.

The syntax `"uri": "http://csvww1160:55003,http://csvww1161:55003"` is expected to work, a draft version of the documentation is available here https://steeltoe-staging.cfapps.io/docs/steeltoe-configuration/#2-2-11-configuring-multiple-urls

**Comment by jluetolf** [comment]
Great, thanks a lot!
