### ISSUE TITLE
The "enabled" setting does no work

### ISSUE THREAD

**Issue by Lightgogogo** [SteeltoeOSS/Configuration#48]
When I set the "spring:cloud:config:enabled"=false just like the Documentation said, the Config Server Client still access then Config Server. My configuration Below:
`"spring": {
    "application": {
      "name": "FrameWorkWebEx"
    },
    "cloud": {
      "config": {
        "enabled": false,
        "failFast": false,
        "retry": { "enabled": true }, 
        "discovery": {
          "enabled": false,
          "serviceId": "CONFIG-SERVER" 
        },
        "uri": "http://localhost:8888" 
      }
    }
  }`

**Comment by dtillman** [comment]
@Lightgogogo : Thanks for pointing it out ..
